version: '3.9'

services:

  redis:
    restart: always
    container_name: muslimboard-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - volume-redis:/data
    networks:
      - muslimboard-network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          # memory: 1000M

  webservice:
    restart: always
    container_name: muslimboard-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - PORT=8012
      - SENTRY_DSN=https://46eb3d7abc35aa698971c1413e695b23@o4506627037790208.ingest.us.sentry.io/4506627059810304
      - REDIS_HOST=muslimboard-redis:6379
      - LOG_LEVEL=debug
      - CACHE_DURATION_IN_HOURS=48
    ports:
      - "8012:8012"
    networks:
      - muslimboard-network
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 300M

networks:
  muslimboard-network:

volumes:
  volume-redis:
