services:

  redis:
    container_name: muslimboard-redis
    image: redis:8.6.2-alpine
    restart: unless-stopped
    # command: redis-server --appendonly yes
    expose:
      - "6379"
    volumes:
      - volume-redis:/data
    networks:
      - muslimboard-network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          # memory: 1000M

  webservice:
    container_name: muslimboard-api
    image: ghcr.io/novalagung/muslimboard-api:latest
    restart: unless-stopped
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8012:8012"
    networks:
      - muslimboard-network
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M

networks:
  muslimboard-network:

volumes:
  volume-redis:
